import React from "react";
import { formatGBP } from "@/app/utils/epc";

export default function BrEstimatedEnergyCosts() {
  return (
    <div id="hem-br-estimated-energy-costs" className="cert-section bg-blue ">
      <div>
        <h3>Estimated energy costs for this home</h3>
        <p className="print-to-inline-span">
          These figures show how much the average household would spend in this
          property for heating, lighting and hot water.
        </p>
        <p className="print-to-inline-span">
          This excludes energy use for running appliances such as TVs, computers
          and cookers, and the benefits of any electricity generated by this
          home (for example, from solar panels).
        </p>
        <p>
          The potential savings in energy costs show the effect of undertaking
          all of the potential improvement measures listed in this report. These
          figures show how much the average household would spend in this
          property for heating, lighting and hot water.
        </p>
      </div>
      <table className="ds_table" style={{ marginTop: "1rem" }}>
        <caption className="ds_visually-hidden">
          Estimated energy costs by category
        </caption>
        <thead>
          <tr>
            <th scope="col">Category</th>
            <th scope="col">Current costs</th>
            <th scope="col">Potential costs</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td scope="row">Heating</td>
            <td>{formatGBP(1763)}</td>
            <td>{formatGBP(1275)}</td>
          </tr>
          <tr>
            <td scope="row">Hot water</td>
            <td>{formatGBP(303)}</td>
            <td>{formatGBP(205)}</td>
          </tr>
          <tr>
            <td scope="row">Lighting</td>
            <td>{formatGBP(202)}</td>
            <td>{formatGBP(135)}</td>
          </tr>
          <tr>
            <td scope="row">Total</td>
            <td>
              <strong>{formatGBP(2268)}</strong>
            </td>
            <td>
              <strong>{formatGBP(1615)}</strong>
            </td>
          </tr>
        </tbody>
      </table>

      <div style={{ marginTop: "1rem" }}>
        <p className="mb-0">
          <strong>Potential future savings</strong>
        </p>
        <p>
          Typical savings per year up to: <strong>653</strong>
        </p>
      </div>
    </div>
  );
}
