export default function CostsAndRecommendationsTable() {
  return (
    <section
      id="costs-and-recommendations"
      aria-labelledby="costs-and-recommendations-title"
    >
      <h2 id="costs-and-recommendations-title">Costs and recommendations</h2>

      <h3>Estimated energy costs for this home</h3>
      <p>
        These figures show how much the average household would spend in this
        property for heating, lighting and hot water. This excludes energy use
        for running appliances such as TVs, computers and cookers, and the
        benefits of any electricity generated by this home.
      </p>
      <p>
        The potential savings in energy costs show the effect of undertaking all
        of the recommended measures listed below.
      </p>

      {/* Placeholder for costs table */}
      <p>[Estimated energy costs table goes here]</p>

      <h3>Recommendations for improvement</h3>
      <p>
        The measures below will improve the energy and environmental performance
        of this dwelling. The performance ratings after improvements listed
        below are cumulative; that is, they assume the improvements have been
        installed in the order that they appear in the table.
      </p>
      <p>
        Before carrying out work, make sure that the appropriate permissions are
        obtained, where necessary. This may include permission from a landlord
        (if you are a tenant) or the need to get a Building Warrant for certain
        types of work.
      </p>

      {/* Placeholder for recommendations table */}
      <p>[Recommendations table goes here]</p>

      <h3>Alternative measures</h3>
      <p>
        There are alternative improvement measures which you could also consider
        for your home. It would be advisable to seek further advice and
        illustration of the benefits and costs of such measures.
      </p>
      <ul>
        <li>Air or ground source heat pump</li>
        <li>Micro CHP</li>
      </ul>

      <h3>Choosing the right improvement package</h3>
      <p>
        For free and impartial advice on choosing suitable measures for your
        property, contact the Home Energy Scotland hotline on 0808 808 2282 or
        go to greenerscotland.org.
      </p>
    </section>
  );
}
