import RatingBadge from "./components/RatingBadge";

export default function CostsAndRecommendationsTable() {
  return (
    <section
      id="costs-and-recommendations"
      aria-labelledby="costs-and-recommendations-title"
    >
      <div className="cert-section">
        <h2 id="costs-and-recommendations-title">Costs and recommendations</h2>

        <h3>Estimated energy costs for this home</h3>

        <table className="ds_table">
          <thead>
            <tr>
              <th scope="col">Energy use</th>
              <th scope="col">Current energy costs</th>
              <th scope="col">Potential energy costs</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Heating</td>
              <td>£2,892 over 3 years</td>
              <td>£1,914 over 3 years</td>
            </tr>

            <tr>
              <td>Hot water</td>
              <td>£1,155 over 3 years</td>
              <td>£609 over 3 years</td>
            </tr>

            <tr>
              <td>Lighting</td>
              <td>£177 over 3 years</td>
              <td>£177 over 3 years</td>
            </tr>

            <tr>
              <td>
                <strong>Totals</strong>
              </td>
              <td>
                <strong>£4,224</strong>
              </td>
              <td>
                <strong>£2,700</strong>
              </td>
            </tr>
          </tbody>
        </table>

        <p>
          <strong>You could save £1,524 over 3 years.</strong>
        </p>

        <p>
          These figures show how much the average household would spend in this
          property for heating, lighting and hot water. This excludes energy use
          for running appliances such as TVs, computers and cookers, and the
          benefits of any electricity generated by this home.
        </p>
        <p>
          The potential savings in energy costs show the effect of undertaking
          all of the recommended measures listed below.
        </p>
      </div>

      <div className="cert-section bg-blue">
        <h3>Recommendations for improvement</h3>
        <p>
          The measures below will improve the energy and environmental
          performance of this dwelling. The performance ratings after
          improvements listed below are cumulative; that is, they assume the
          improvements have been installed in the order that they appear in the
          table.
        </p>
        <p>
          Before carrying out work, make sure that the appropriate permissions
          are obtained, where necessary. This may include permission from a
          landlord (if you are a tenant) or the need to get a Building Warrant
          for certain types of work.
        </p>

        <table className="ds_table">
          <thead>
            <tr>
              <th scope="col">Recommended measures</th>
              <th scope="col">Indicative cost</th>
              <th scope="col">Typical saving per year</th>
              <th scope="col">Rating after improvement: Energy</th>
              <th scope="col">Rating after improvement: Environment</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Floor insulation</td>
              <td>£800 – £1,200</td>
              <td>£148</td>
              <td>
                <RatingBadge variant="energy" band="D" score={58} />
              </td>
              <td>
                <RatingBadge variant="environment" band="E" score={53} />
              </td>
            </tr>

            <tr>
              <td>Replace boiler with new condensing boiler</td>
              <td>£2,200 – £3,000</td>
              <td>£305</td>
              <td>
                <RatingBadge variant="energy" band="D" score={68} />
              </td>
              <td>
                <RatingBadge variant="environment" band="D" score={65} />
              </td>
            </tr>

            <tr>
              <td>Solar water heating</td>
              <td>£4,000 – £6,000</td>
              <td>£55</td>
              <td>
                <RatingBadge variant="energy" band="C" score={70} />
              </td>
              <td>
                <RatingBadge variant="environment" band="D" score={68} />
              </td>
            </tr>

            <tr>
              <td>Solar photovoltaic panels, 2.5&nbsp;kWp</td>
              <td>£9,000 – £14,000</td>
              <td>£223</td>
              <td>
                <RatingBadge variant="energy" band="C" score={79} />
              </td>
              <td>
                <RatingBadge variant="environment" band="C" score={76} />
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      <div className="cert-section">
        <h3>Alternative measures</h3>
        <p>
          There are alternative improvement measures which you could also
          consider for your home. It would be advisable to seek further advice
          and illustration of the benefits and costs of such measures.
        </p>
        <ul>
          <li>Air or ground source heat pump</li>
          <li>Micro CHP</li>
        </ul>
      </div>
      <div className="cert-section bg-grey">
        <h3>Choosing the right improvement package</h3>
        <p>
          For free and impartial advice on choosing suitable measures for your
          property, contact the Home Energy Scotland hotline on{" "}
          <a className="ds_link" href="tel:08088082282">
            0808 808 2282
          </a>{" "}
          or go to{" "}
          <a
            href="http://greenerscotland.org"
            target="_blank"
            rel="noopener noreferrer"
          >
            greenerscotland.org
          </a>
        </p>
      </div>
    </section>
  );
}
