import React from "react";
import { formatGBP } from "@/app/utils/epc";

export default function BrEstimatedEnergyCosts() {
  return (
    <div
      id="br-estimated-energy-costs"
      style={{ background: "#DAEEF7", padding: "16px" }}
    >
      <div>
        <h3>Estimated energy costs for this home</h3>
        <p>
          These figures show how much the average household would spend in this
          property for heating, lighting and hot water.
        </p>
        <p>
          This excludes energy use for running appliances such as TVs, computers
          and cookers, and the benefits of any electricity generated by this
          home (for example, from photovoltaic panels).
        </p>
        <p>
          The potential savings in energy costs show the effect of undertaking
          all of the recommended measures listed in this report.
        </p>
      </div>
      <table className="ds_table" style={{ marginTop: "1rem" }}>
        <caption className="ds_visually-hidden">
          Estimated energy costs by category
        </caption>
        <thead>
          <tr>
            <th scope="col">TBC</th>
            <th scope="col">Current costs</th>
            <th scope="col">Potential costs</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row">Heating</th>
            <td>{formatGBP(1763)}</td>
            <td>{formatGBP(1275)}</td>
          </tr>
          <tr>
            <th scope="row">Hot water</th>
            <td>{formatGBP(303)}</td>
            <td>{formatGBP(205)}</td>
          </tr>
          <tr>
            <th scope="row">Lighting</th>
            <td>{formatGBP(202)}</td>
            <td>{formatGBP(135)}</td>
          </tr>
          <tr>
            <th scope="row">Total</th>
            <td>
              <strong>{formatGBP(2268)}</strong>
            </td>
            <td>
              <strong>{formatGBP(1615)}</strong>
            </td>
          </tr>
        </tbody>
      </table>

      <div style={{ marginTop: "1rem" }}>
        <p className="ds_hint-text" style={{ marginBottom: 0 }}>
          Potential future savings
        </p>
        <p>
          Typical savings per year up to: <strong>653</strong>
        </p>
      </div>
    </div>
  );
}
